### ISSUE TITLE
Weird glitch screen

### ISSUE THREAD

**Issue by colbster937** [jothi-prasath/SmallSur#5]
I just installed on my raspberry pi 5 and i get this screen
<img width="1419" alt="image" src="https://github.com/jothi-prasath/SmallSur/assets/96893162/23e513cc-8407-43f8-8fab-6ab887795e5b">
how do i uninstall it from the terminal?

**Comment by jothi-prasath** [comment]
run this
```
git clone https://github.com/jothi-prasath/WhiteSur-gtk-theme.git --depth=1
sudo WhiteSur-gtk-theme/tweaks.sh -g -r
```
