### ISSUE TITLE
Provide Actual Instructions or Script it

### ISSUE THREAD

**Issue by TCB13** [jothi-prasath/SmallSur#9]
Hello,

Can you provide actual instructions how how get it to look like this? https://github.com/jothi-prasath/SmallSur/raw/master/img/sample2.png

> Adjust the Plank settings to customize the dock appearance and behavior.
> Configure the XFCE panel to organize and manage the top bar elements.

It isn't clear what needs to be changed.

**Comment by jothi-prasath** [comment]
> Adjust the Plank settings to customize the dock appearance and behavior.
Configure the XFCE panel to organize and manage the top bar elements.

Adjust the settings depending on screen size/aspect ratio/preference. other than that the script itself explains the instructions.

**Comment by TCB13** [comment]
> other than that the script itself explains the instructions.

Why doesnt the script make all the required changes then. By just running the script you don't get the advertised desktop, not by a long shot.
